package Views;

import Controllers.EntregaController;
import Models.Configurations;
import Models.Entrega;
import Models.Tarea;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class FrameCalificarEntregas extends javax.swing.JFrame {

    private EntregaController _ec = EntregaController.getInstance();
    private Tarea tarea;
    private List<Entrega> entregas;
    private boolean comboboxCargado;
    private boolean ableToLeft;
    private boolean ableToRight;

    /**
     * Creates new form FrameCalificarEntregas
     */
    public FrameCalificarEntregas(Tarea tarea) {
        initComponents();
        Configurations.setApplicationIcon(this);
        this.tarea = tarea;
        initializeView();
        SwingUtilities.invokeLater(() -> cmbEstudiantes.requestFocusInWindow());
    }

    private void initializeView() {
        Configurations.setImageToLabel(btnLeft, "/icon_left.png");
        Configurations.setImageToLabel(btnRight, "/icon_right.png");
        Configurations.addHoverEffectToLabel(btnLeft, "/icon_left.png");
        Configurations.addHoverEffectToLabel(btnRight, "/icon_right.png");

        cargarComboBox();        
    }

    private void cargarComboBox() {
        comboboxCargado = false;
        txtCalificacion.setText("");
        entregas = _ec.getEntregasByIdTarea(tarea.getIdTarea());
        entregas.sort(Comparator
                .comparingInt(Entrega::getIdEntrega) // Primero por idEntrega
                .thenComparing(e -> e.getCalificacion() == null ? Integer.MAX_VALUE : e.getCalificacion())); // Luego por calificacion

        //Collections.reverse(entregas);
        DefaultComboBoxModel<Entrega> model = new DefaultComboBoxModel<>();

        if (!rdbVerTodos.isSelected()) {
            entregas = entregas.stream()
                    .filter(entrega -> entrega.getCalificacion() != null && entrega.getCalificacion() < 0)
                    .collect(Collectors.toList());
        }
        for (Entrega e : entregas) {
            model.addElement(e);
        }
        cmbEstudiantes.setModel(model);
        if (cmbEstudiantes.getItemCount() > 0) {
            comboboxCargado = true;
        }
        evaluarBotones();
        cargarEntrega();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlEstudiantes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rdbVerTodos = new javax.swing.JRadioButton();
        rdbVerCalif = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmbEstudiantes = new javax.swing.JComboBox<>();
        btnLeft = new javax.swing.JLabel();
        btnRight = new javax.swing.JLabel();
        pnlTarea = new javax.swing.JPanel();
        pnlTítulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        pnlDescripcion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlArchivos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlCalificar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCalificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STM - Calificar");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlEncabezado.setBackground(new java.awt.Color(51, 102, 0));
        pnlEncabezado.setPreferredSize(new java.awt.Dimension(561, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calificar Entregas");
        pnlEncabezado.add(jLabel1);

        getContentPane().add(pnlEncabezado);

        pnlEstudiantes.setBackground(new java.awt.Color(255, 255, 255));
        pnlEstudiantes.setPreferredSize(new java.awt.Dimension(563, 92));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(279, 82));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(279, 37));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(rdbVerTodos);
        rdbVerTodos.setText("Ver todos");
        rdbVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVerTodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbVerCalif);
        rdbVerCalif.setSelected(true);
        rdbVerCalif.setText("Ver sin calificación");
        rdbVerCalif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVerCalifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbVerCalif)
                .addGap(18, 18, 18)
                .addComponent(rdbVerTodos)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbVerCalif)
                    .addComponent(rdbVerTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(279, 45));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cmbEstudiantes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEstudiantesItemStateChanged(evt);
            }
        });

        btnLeft.setIcon(new javax.swing.ImageIcon("C:\\Users\\Xavier\\OneDrive - Universidad de Guayaquil\\(AAB) UG\\Student_Task_Manager\\src\\main\\resources\\icon_left.png")); // NOI18N
        btnLeft.setText("jLabel2");
        btnLeft.setMaximumSize(new java.awt.Dimension(27, 27));
        btnLeft.setMinimumSize(new java.awt.Dimension(27, 27));
        btnLeft.setPreferredSize(new java.awt.Dimension(27, 27));
        btnLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeftMouseClicked(evt);
            }
        });

        btnRight.setIcon(new javax.swing.ImageIcon("C:\\Users\\Xavier\\OneDrive - Universidad de Guayaquil\\(AAB) UG\\Student_Task_Manager\\src\\main\\resources\\icon_right.png")); // NOI18N
        btnRight.setText("jLabel3");
        btnRight.setMaximumSize(new java.awt.Dimension(27, 27));
        btnRight.setMinimumSize(new java.awt.Dimension(27, 27));
        btnRight.setPreferredSize(new java.awt.Dimension(27, 27));
        btnRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRightMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3);

        pnlEstudiantes.add(jPanel1);

        getContentPane().add(pnlEstudiantes);

        pnlTarea.setBackground(new java.awt.Color(245, 255, 255));
        pnlTarea.setPreferredSize(new java.awt.Dimension(561, 320));
        pnlTarea.setLayout(new javax.swing.BoxLayout(pnlTarea, javax.swing.BoxLayout.Y_AXIS));

        pnlTítulo.setBackground(new java.awt.Color(245, 255, 255));
        pnlTítulo.setPreferredSize(new java.awt.Dimension(561, 60));
        pnlTítulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        txtTitulo.setEditable(false);
        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitulo.setFocusable(false);
        txtTitulo.setPreferredSize(new java.awt.Dimension(291, 30));
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        pnlTítulo.add(txtTitulo);

        pnlTarea.add(pnlTítulo);

        pnlDescripcion.setBackground(new java.awt.Color(245, 255, 255));
        pnlDescripcion.setPreferredSize(new java.awt.Dimension(301, 170));
        pnlDescripcion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(291, 150));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setFocusable(false);
        jScrollPane1.setViewportView(txtDescripcion);

        pnlDescripcion.add(jScrollPane1);

        pnlTarea.add(pnlDescripcion);

        pnlArchivos.setBackground(new java.awt.Color(245, 255, 255));
        pnlArchivos.setPreferredSize(new java.awt.Dimension(301, 90));
        pnlArchivos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel7.setPreferredSize(new java.awt.Dimension(291, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Archivos subidos...");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlArchivos.add(jPanel7);

        pnlTarea.add(pnlArchivos);

        getContentPane().add(pnlTarea);

        pnlCalificar.setBackground(new java.awt.Color(161, 255, 255));
        pnlCalificar.setPreferredSize(new java.awt.Dimension(313, 48));

        jPanel6.setBackground(new java.awt.Color(161, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Calificación:");

        txtCalificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalificacionKeyTyped(evt);
            }
        });

        jLabel3.setText("/100");

        btnCalificar.setBackground(new java.awt.Color(0, 51, 51));
        btnCalificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalificar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificar.setText("Calificar");
        btnCalificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalificar.setBorderPainted(false);
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnCalificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCalificar.add(jPanel6);

        getContentPane().add(pnlCalificar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeftMouseClicked
        if (comboboxCargado && ableToLeft)
            cmbEstudiantes.setSelectedIndex(cmbEstudiantes.getSelectedIndex() - 1);
    }//GEN-LAST:event_btnLeftMouseClicked

    private void cmbEstudiantesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEstudiantesItemStateChanged
        if (comboboxCargado) {
            evaluarBotones();
            cargarEntrega();
        }

    }//GEN-LAST:event_cmbEstudiantesItemStateChanged

    private void evaluarBotones() {
        ableToRight = false;
        ableToLeft = false;
        btnLeft.setEnabled(true);
        btnRight.setEnabled(true);
        if (cmbEstudiantes.getSelectedIndex() == 0) {
            btnLeft.setEnabled(false);
            ableToRight = true;
            ableToLeft = false;
        }
        if (cmbEstudiantes.getSelectedIndex() == cmbEstudiantes.getItemCount() - 1) {
            btnRight.setEnabled(false);
            ableToRight = false;
            ableToLeft = true;
        }
    }

    private void cargarEntrega() {
        txtTitulo.setText("");
        txtDescripcion.setText("");
        txtCalificacion.setText("");
        for (Entrega e : entregas) {
            Entrega entregaCmb = (Entrega) cmbEstudiantes.getSelectedItem();
            if (e.getIdEntrega() == entregaCmb.getIdEntrega()) {
                txtTitulo.setText(e.getTitulo());
                txtDescripcion.setText(e.getDescripcion());
                if (e.getCalificacion() >= 0) 
                    txtCalificacion.setText("" + e.getCalificacion());                
            }
        }
        cmbEstudiantes.requestFocusInWindow();
    }

    private void rdbVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVerTodosActionPerformed
        cargarComboBox();
    }//GEN-LAST:event_rdbVerTodosActionPerformed

    private void rdbVerCalifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVerCalifActionPerformed
        cargarComboBox();
    }//GEN-LAST:event_rdbVerCalifActionPerformed

    private void btnRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightMouseClicked
        if (comboboxCargado && ableToRight){
            cmbEstudiantes.setSelectedIndex(cmbEstudiantes.getSelectedIndex() + 1);              
        }
    }//GEN-LAST:event_btnRightMouseClicked

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        if(cmbEstudiantes.getItemCount()==0){
            JOptionPane.showMessageDialog(this, "No hay estudiantes por calificar.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String strCalificacion = txtCalificacion.getText().trim();
        int calificacion = 0;
        try{
            boolean quitarCalif = false;
            if(strCalificacion.equals("")) quitarCalif = true;
            else calificacion = Integer.parseInt(strCalificacion);
            if(calificacion < 0 || calificacion > 100) {
                JOptionPane.showMessageDialog(this, "No ha ingresado una calificación válida.","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(quitarCalif) calificacion = -1;
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No ha ingresado una calificación válida.","Error",JOptionPane.ERROR_MESSAGE);
            txtCalificacion.setText("");
            txtCalificacion.requestFocusInWindow();
            return;
        }
        Entrega entregaSeleccionada = (Entrega) cmbEstudiantes.getSelectedItem();
        entregaSeleccionada.setCalificacion(calificacion);
        _ec.updateEntrega(entregaSeleccionada);
        cmbEstudiantes.requestFocusInWindow();        
        JOptionPane.showMessageDialog(this, "Calificación actualizada con éxito.","Información",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCalificarActionPerformed

    private void txtCalificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalificacionKeyTyped
        char c = evt.getKeyChar();
        if(txtCalificacion.getText().length() == 3) evt.consume();
    }//GEN-LAST:event_txtCalificacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JLabel btnLeft;
    private javax.swing.JLabel btnRight;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Entrega> cmbEstudiantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlArchivos;
    private javax.swing.JPanel pnlCalificar;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlEstudiantes;
    private javax.swing.JPanel pnlTarea;
    private javax.swing.JPanel pnlTítulo;
    private javax.swing.JRadioButton rdbVerCalif;
    private javax.swing.JRadioButton rdbVerTodos;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
