package Views;

import Controllers.EntregaController;
import Controllers.UsuarioController;
import Models.Configurations;
import Models.Entrega;
import Models.Materia;
import Models.Tarea;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class FrameEntrega extends javax.swing.JFrame {

    private Entrega entrega;
    private EntregaController _ec = EntregaController.getInstance();
    private int modo; // 1. Editando, 2. Nuevo
    private boolean soloLectura;
    private FrameTareaEstudiante parent;
    private Tarea tarea;

    /**
     * Creates new form FrameVerTarea
     */
    public FrameEntrega(Entrega entrega, boolean soloLectura, FrameTareaEstudiante parent) { // Editando entrega
        initComponents();        
        this.parent = parent;
        this.entrega = entrega;
        this.modo = 1;
        this.soloLectura = soloLectura;
        this.tarea = entrega.getTarea();        
        iniciarForm();
    }

    public FrameEntrega(Tarea tarea, FrameTareaEstudiante parent) { // Creando nueva
        initComponents();
        this.parent = parent;
        this.soloLectura = false;
        this.entrega = null;
        this.modo = 2;
        this.tarea = tarea;
        iniciarForm();
    }

    private void iniciarForm() {
        Configurations.setApplicationIcon(this);
        SwingUtilities.invokeLater(() -> btnEnviarGuardar.requestFocusInWindow());
        pnlMessage.setVisible(false);
        if (modo == 1) {
            lblTitle.setText("Entrega");
            cargarEntrega();
            if (soloLectura){
                SwingUtilities.invokeLater(() -> pblTitle.requestFocusInWindow());
                deshabilitarEdicion();                
            } 
            
        }
        if (modo == 2) {
            lblTitle.setText("Creando Entrega");
            colocarPlaceHolders();
        }

    }
    
    private void colocarPlaceHolders(){
        Configurations.addPlaceholder(txtTitle, "Título");
        Configurations.addPlaceholder(txtDescripcion, "Descripción...");
    }

    private void cargarEntrega() {
        txtTitle.setText(entrega.getTitulo());
        txtDescripcion.setText(entrega.getDescripcion());
        lblFecha.setText(entrega.getFechaEntrega().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
        btnEnviarGuardar.setText("Guardar");
    }

    private void deshabilitarEdicion() {
        txtTitle.setEditable(false);
        txtDescripcion.setEditable(false);
        btnEnviarGuardar.setEnabled(false);
        pnlMessage.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        pnlDescripcion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlArchivos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlFecha = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        pnlBotonesEnvio = new javax.swing.JPanel();
        btnEnviarGuardar = new javax.swing.JButton();
        pnlMessage = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STM - Entrega");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pblTitle.setBackground(new java.awt.Color(102, 0, 102));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Entrega");
        pblTitle.add(lblTitle);

        getContentPane().add(pblTitle);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitle.setMaximumSize(new java.awt.Dimension(291, 30));
        txtTitle.setMinimumSize(new java.awt.Dimension(291, 30));
        txtTitle.setPreferredSize(new java.awt.Dimension(291, 30));
        pnlTitle.add(txtTitle);

        pnlPrincipal.add(pnlTitle);

        pnlDescripcion.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(291, 115));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(291, 115));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(291, 115));

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setMaximumSize(new java.awt.Dimension(291, 115));
        txtDescripcion.setMinimumSize(new java.awt.Dimension(291, 115));
        txtDescripcion.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(txtDescripcion);

        pnlDescripcion.add(jScrollPane1);

        pnlPrincipal.add(pnlDescripcion);

        pnlArchivos.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setMaximumSize(new java.awt.Dimension(291, 85));
        jPanel3.setMinimumSize(new java.awt.Dimension(291, 85));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Archivos subidos...");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Subir Archivo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pnlArchivos.add(jPanel3);

        pnlPrincipal.add(pnlArchivos);

        pnlFecha.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Fecha envío:");
        jPanel1.add(jLabel1);

        lblFecha.setText(" - - -");
        lblFecha.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lblFecha);

        pnlFecha.add(jPanel1);

        pnlPrincipal.add(pnlFecha);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        pnlBotonesEnvio.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonesEnvio.setMaximumSize(new java.awt.Dimension(256, 49));
        pnlBotonesEnvio.setMinimumSize(new java.awt.Dimension(256, 49));

        btnEnviarGuardar.setBackground(new java.awt.Color(0, 153, 51));
        btnEnviarGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviarGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarGuardar.setText("Enviar");
        btnEnviarGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviarGuardar.setBorderPainted(false);
        btnEnviarGuardar.setMaximumSize(new java.awt.Dimension(113, 37));
        btnEnviarGuardar.setMinimumSize(new java.awt.Dimension(113, 37));
        btnEnviarGuardar.setPreferredSize(new java.awt.Dimension(113, 37));
        btnEnviarGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarGuardarActionPerformed(evt);
            }
        });
        pnlBotonesEnvio.add(btnEnviarGuardar);

        pnlBotones.add(pnlBotonesEnvio);

        pnlPrincipal.add(pnlBotones);

        pnlMessage.setBackground(new java.awt.Color(255, 255, 255));
        pnlMessage.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        lblMessage.setForeground(new java.awt.Color(51, 51, 51));
        lblMessage.setText("No se permiten realizar cambios.");
        pnlMessage.add(lblMessage);

        pnlPrincipal.add(pnlMessage);

        getContentPane().add(pnlPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarGuardarActionPerformed
        String msg;        
        try {
            if (modo == 1) {
                // 1. Editando
                Entrega entregaEditada = obtenerDatosEntregaNueva();
                entregaEditada.setIdEntrega(entrega.getIdEntrega());                
                _ec.updateEntrega(entregaEditada);
                msg = "Entrega actualizada con éxito.";
            } else {
                // 2. Nuevo
                entrega = obtenerDatosEntregaNueva();
                _ec.addEntrega(entrega);
                msg = "Entrega enviada con éxito.";
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, msg, "Información", JOptionPane.INFORMATION_MESSAGE);
        parent.initializeView();        
        this.dispose();
    }//GEN-LAST:event_btnEnviarGuardarActionPerformed

    private Entrega obtenerDatosEntregaNueva() throws Exception {
        String titulo = txtTitle.getText();
        String desc = txtDescripcion.getText();
        if (titulo.equals("") || desc.equals("")) {
            throw new Exception("Rellene todos los campos.");
        }

        int idTarea = tarea.getIdTarea();
        int idEstudiante = UsuarioController.getMainUser().getIdPersona();
        LocalDateTime fechaEntrega = LocalDateTime.now();
        return new Entrega(idTarea, idEstudiante, fechaEntrega, titulo, desc);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pblTitle;
    private javax.swing.JPanel pnlArchivos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBotonesEnvio;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlFecha;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
