package Views;

import Controllers.EntregaController;
import Controllers.TareaController;
import Controllers.UsuarioController;
import Models.Configurations;
import Models.Entrega;
import Models.Materia;
import Models.Tarea;
import Views.Panels.PanelCalificacionTareas;
import Views.Panels.PanelTareas;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class FrameTareaDocente extends javax.swing.JFrame {
    // Variables
    private Tarea tarea;
    private int idMateria;
    private EntregaController _ec = EntregaController.getInstance();    
    private int modo; // 1. Edición 2. Nueva
    private TareaController _tc = TareaController.getInstance();
    private JPanel parent;
    
    public FrameTareaDocente(Tarea tarea, PanelTareas parent) { // 1. Edición
        initComponents();
        this.parent = parent;
        this.tarea = tarea;
        this.idMateria = tarea.getIdMateria();
        this.modo = 1;
        initializeView();
    }
    
    public FrameTareaDocente(Tarea tarea, PanelCalificacionTareas parent) { // 1. Edición (Llamado desde calificaciones
        initComponents();
        this.parent = parent;
        this.tarea = tarea;
        this.idMateria = tarea.getIdMateria();
        this.modo = 1;
        initializeView();
    }
    
    public FrameTareaDocente(PanelTareas parent, int idMateria) { // 2. Nueva
        initComponents();
        this.parent = parent;
        this.idMateria = idMateria;
        this.tarea = null;
        this.modo = 2;
        initializeView();
    }
    
    public final void initializeView(){ 
        Configurations.setApplicationIcon(this);
        SwingUtilities.invokeLater(() -> btnGuardar.requestFocusInWindow());
        if(modo==1){
            cargarDatosTarea();
            btnVerEntregas.setVisible(true);
        }
        if(modo==2){
            colocarPlaceHolders();
            btnVerEntregas.setVisible(false);
        }
    }
    
    private void colocarPlaceHolders(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");        
        txtFechaApertura.setText(LocalDateTime.now().format(dtf));
        txtFechaEntrega.setText(LocalDateTime.now().format(dtf));
        Configurations.addPlaceholder(txtTitle, "Título");
        Configurations.addPlaceholder(txtDescripcion, "Descripción");
    }
    
    private void cargarDatosTarea(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        txtFechaApertura.setText(tarea.getFechaCreacion().format(dtf));
        txtFechaEntrega.setText(tarea.getFechaEntrega().format(dtf));
        txtTitle.setText(tarea.getTitulo());
        txtDescripcion.setText(tarea.getDescripcion());
        List<Entrega> entregas = _ec.getEntregasByIdTarea(tarea.getIdTarea());
        btnVerEntregas.setText("Ver Entregas (" + entregas.size() + ")");
        if(entregas.isEmpty()) btnVerEntregas.setEnabled(false);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlFechas = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaApertura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        pnlButton = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        pnlTitle = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        pnlDescripcion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlArchivos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        pnlBotonesEnvio = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnVerEntregas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STM - Tarea");
        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(367, 492));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlEncabezado.setBackground(new java.awt.Color(0, 153, 153));
        pnlEncabezado.setMinimumSize(new java.awt.Dimension(337, 41));
        pnlEncabezado.setPreferredSize(new java.awt.Dimension(337, 41));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Tarea");
        pnlEncabezado.add(lblTitle);

        getContentPane().add(pnlEncabezado);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        pnlFechas.setBackground(new java.awt.Color(255, 255, 255));
        pnlFechas.setLayout(new javax.swing.BoxLayout(pnlFechas, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(257, 74));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Fecha de Apertura:");
        jPanel4.add(jLabel1);

        txtFechaApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAperturaActionPerformed(evt);
            }
        });
        jPanel4.add(txtFechaApertura);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Fecha de Entrega:");
        jPanel4.add(jLabel2);
        jPanel4.add(txtFechaEntrega);

        jPanel5.add(jPanel4);

        pnlFechas.add(jPanel5);

        pnlButton.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminar.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pnlFechas.add(pnlButton);

        jPanel1.add(pnlFechas);

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitle.setMaximumSize(new java.awt.Dimension(291, 30));
        txtTitle.setMinimumSize(new java.awt.Dimension(291, 30));
        txtTitle.setPreferredSize(new java.awt.Dimension(291, 30));
        pnlTitle.add(txtTitle);

        jPanel1.add(pnlTitle);

        pnlDescripcion.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(291, 115));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(291, 115));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(291, 115));

        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setMaximumSize(new java.awt.Dimension(291, 115));
        txtDescripcion.setMinimumSize(new java.awt.Dimension(291, 115));
        jScrollPane1.setViewportView(txtDescripcion);

        pnlDescripcion.add(jScrollPane1);

        jPanel1.add(pnlDescripcion);

        pnlArchivos.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setMaximumSize(new java.awt.Dimension(291, 78));
        jPanel3.setMinimumSize(new java.awt.Dimension(291, 78));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Archivos subidos...");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Subir Archivo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pnlArchivos.add(jPanel3);

        jPanel1.add(pnlArchivos);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        pnlBotonesEnvio.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonesEnvio.setMaximumSize(new java.awt.Dimension(256, 49));
        pnlBotonesEnvio.setMinimumSize(new java.awt.Dimension(256, 49));

        btnGuardar.setBackground(new java.awt.Color(51, 102, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setMaximumSize(new java.awt.Dimension(113, 37));
        btnGuardar.setMinimumSize(new java.awt.Dimension(113, 37));
        btnGuardar.setPreferredSize(new java.awt.Dimension(113, 37));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVerEntregas.setBackground(new java.awt.Color(51, 51, 51));
        btnVerEntregas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerEntregas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEntregas.setText("Ver Entregas (20)");
        btnVerEntregas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerEntregas.setBorderPainted(false);
        btnVerEntregas.setMaximumSize(new java.awt.Dimension(113, 37));
        btnVerEntregas.setMinimumSize(new java.awt.Dimension(113, 37));
        btnVerEntregas.setPreferredSize(new java.awt.Dimension(113, 37));
        btnVerEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerEntregasMouseClicked(evt);
            }
        });
        btnVerEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEntregasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesEnvioLayout = new javax.swing.GroupLayout(pnlBotonesEnvio);
        pnlBotonesEnvio.setLayout(pnlBotonesEnvioLayout);
        pnlBotonesEnvioLayout.setHorizontalGroup(
            pnlBotonesEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlBotonesEnvioLayout.setVerticalGroup(
            pnlBotonesEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesEnvioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotonesEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVerEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlBotones.add(pnlBotonesEnvio);

        jPanel1.add(pnlBotones);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Tarea nuevaTarea;
        String msg;
        try{
           nuevaTarea = obtenerDatosTarea();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(modo == 1){ // Edicion
            nuevaTarea.setIdTarea(tarea.getIdTarea());
           _tc.updateTarea(nuevaTarea);
           msg = "Tarea actualizada con éxito.";
        }else{ // Nueva
            _tc.addTarea(nuevaTarea);
            msg = "Tarea creada con éxito";
        }
        
        JOptionPane.showMessageDialog(this, msg, "Información", JOptionPane.INFORMATION_MESSAGE); 
        if(parent instanceof PanelTareas panelTareas) panelTareas.agregarTareas();
        else ((PanelCalificacionTareas) parent).cargarTabla();
        this.dispose();        
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private Tarea obtenerDatosTarea() throws Exception{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime fechaApertura;
        LocalDateTime fechaEntrega;
        String strFechaApertura = txtFechaApertura.getText().trim();
        String strFechaEntrega = txtFechaEntrega.getText().trim();
        String titulo = txtTitle.getText();
        String descripcion = txtDescripcion.getText();
        
        if(strFechaApertura.equals("") ||
           strFechaEntrega.equals("") ||
           titulo.equals("") ||
           descripcion.equals(""))
            throw new Exception("Rellene todos los campos.");        
        
        try{
            fechaApertura = LocalDateTime.parse(strFechaApertura, dtf);
            fechaEntrega = LocalDateTime.parse(strFechaEntrega, dtf);
        }catch(Exception e){
            throw new Exception("El formato de la fecha es incorrecto. Use 'dd/MM/yyyy HH:mm'.");
        }

        if(fechaApertura.isAfter(fechaEntrega))
            throw new Exception("La fecha y hora de entrega no puede ser menor a la de apertura.");
        
        return new Tarea(0, idMateria, titulo, descripcion, fechaApertura, fechaEntrega);
    }
    
    private void txtFechaAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAperturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAperturaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar esta tarea? (Esta acción no se puede deshacer)", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            _ec.deleteEntregasByIdTarea(tarea.getIdTarea());
            _tc.deleteTarea(tarea.getIdTarea());            
            JOptionPane.showMessageDialog(this, "Tarea borrada con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE);
            if(parent instanceof PanelTareas panelTareas) panelTareas.agregarTareas();
            else ((PanelCalificacionTareas) parent).cargarTabla();
            this.dispose();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(parent instanceof PanelTareas panelTareas) panelTareas.agregarTareas();
        else ((PanelCalificacionTareas) parent).cargarTabla();
    }//GEN-LAST:event_formWindowClosing

    private void btnVerEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEntregasMouseClicked
         if (evt.getClickCount() == 1 && !evt.isConsumed() && btnVerEntregas.isEnabled()) {
            evt.consume();
            FrameCalificarEntregas fce = new FrameCalificarEntregas(tarea);
            fce.setVisible(true);
         }
    }//GEN-LAST:event_btnVerEntregasMouseClicked

    private void btnVerEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerEntregasActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerEntregas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlArchivos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBotonesEnvio;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlFechas;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFechaApertura;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

}
