package Views;

import Controllers.UsuarioController;
import Models.Configurations;
import Models.Usuario;
import Views.Panels.PanelCalificacionMaterias;
import Views.Panels.PanelMateria;
import Views.Panels.PanelTodasMaterias;
import Views.Panels.PanelVacio;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {        
        initComponents();
        Configurations.setApplicationIcon(this);
        initialConfigurations();
        lblName.setText(UsuarioController.getMainUser().getPersona().getNombre() + " " + UsuarioController.getMainUser().getPersona().getApellido());
        lblRol.setText(UsuarioController.getMainUser().getPersona().getRol().getDescripcion());
    }    

    private void initialConfigurations() {
        Configurations.setImageToLabel(lblLogo, "/stm_logo.png");
    }

    public void initializePanel(JPanel panel) {
        panelMain.removeAll();
        panelMain.add(panel, BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }
    
    public void forzarPanelMateria(int idMateria){        
        btnSubjects.setSelected(true);
        initializePanel(new PanelMateria(idMateria, this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainButtons = new javax.swing.ButtonGroup();
        panelMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnSubjects = new javax.swing.JToggleButton();
        btnScores = new javax.swing.JToggleButton();
        btnNotifications = new javax.swing.JToggleButton();
        btnSettings = new javax.swing.JToggleButton();
        lblName = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Task Manager");
        setResizable(false);

        panelMenu.setBackground(new java.awt.Color(0, 102, 204));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stm_logo.png"))); // NOI18N
        lblLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblLogo.setMaximumSize(new java.awt.Dimension(98, 78));

        btnSubjects.setBackground(new java.awt.Color(0, 102, 204));
        mainButtons.add(btnSubjects);
        btnSubjects.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubjects.setForeground(new java.awt.Color(255, 255, 255));
        btnSubjects.setText("Materias");
        btnSubjects.setBorder(null);
        btnSubjects.setBorderPainted(false);
        btnSubjects.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnSubjectsItemStateChanged(evt);
            }
        });
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });

        btnScores.setBackground(new java.awt.Color(0, 102, 204));
        mainButtons.add(btnScores);
        btnScores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnScores.setForeground(new java.awt.Color(255, 255, 255));
        btnScores.setText("Calificaciones");
        btnScores.setBorder(null);
        btnScores.setBorderPainted(false);
        btnScores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnScoresItemStateChanged(evt);
            }
        });
        btnScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoresActionPerformed(evt);
            }
        });

        btnNotifications.setBackground(new java.awt.Color(0, 102, 204));
        mainButtons.add(btnNotifications);
        btnNotifications.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNotifications.setForeground(new java.awt.Color(255, 255, 255));
        btnNotifications.setText("Notificaciones");
        btnNotifications.setBorder(null);
        btnNotifications.setBorderPainted(false);
        btnNotifications.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnNotificationsItemStateChanged(evt);
            }
        });
        btnNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationsActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(0, 102, 204));
        mainButtons.add(btnSettings);
        btnSettings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSettings.setText("Configuración");
        btnSettings.setBorder(null);
        btnSettings.setBorderPainted(false);
        btnSettings.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnSettingsItemStateChanged(evt);
            }
        });
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Nombre Apellido");
        lblName.setFocusable(false);

        lblRol.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setText("Estudiante");
        lblRol.setFocusable(false);

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Cerrar Sesión");
        btnLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNotifications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnScores, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubjectsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnSubjectsItemStateChanged
        toggleButtonBackground(btnSubjects);
    }//GEN-LAST:event_btnSubjectsItemStateChanged

    private void btnScoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnScoresItemStateChanged
        toggleButtonBackground(btnScores);
    }//GEN-LAST:event_btnScoresItemStateChanged

    private void btnNotificationsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnNotificationsItemStateChanged
        toggleButtonBackground(btnNotifications);
    }//GEN-LAST:event_btnNotificationsItemStateChanged

    private void btnSettingsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnSettingsItemStateChanged
        toggleButtonBackground(btnSettings);
    }//GEN-LAST:event_btnSettingsItemStateChanged

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
        initializePanel(new PanelTodasMaterias(this));
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            FrameLogin fl = new FrameLogin();
            fl.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoresActionPerformed
        initializePanel(new PanelCalificacionMaterias(this));
    }//GEN-LAST:event_btnScoresActionPerformed

    private void btnNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationsActionPerformed
        initializePanel(new PanelVacio());
    }//GEN-LAST:event_btnNotificationsActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        initializePanel(new PanelVacio());
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void toggleButtonBackground(JToggleButton boton) {
        if (boton.isSelected()) boton.setBackground(new Color(0, 51, 153));
        else boton.setBackground(new Color(0, 102, 204));        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JToggleButton btnNotifications;
    private javax.swing.JToggleButton btnScores;
    private javax.swing.JToggleButton btnSettings;
    private javax.swing.JToggleButton btnSubjects;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRol;
    private javax.swing.ButtonGroup mainButtons;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
