package Views.Panels;

import Controllers.MateriaController;
import Models.Materia;
import Views.FrameMain;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

public class PanelMateria extends javax.swing.JPanel {
    private int idMateria;
    private MateriaController _mc = MateriaController.getInstance();
    private FrameMain parent;
    /**
     * Creates new form PanelMaterias
     */
    public PanelMateria(int idMateria, FrameMain parent) {
        initComponents();
        this.parent = parent;
        this.idMateria = idMateria;
        btnTasks.setBackground(new Color(102, 0, 255));
        initializePanel(new PanelTareas(idMateria, parent));        
        Materia materia = _mc.getMateriaById(idMateria);
        lblMateria.setText(materia.getNombre());
    }

    private void initializePanel(JPanel panel) {
        panelMain.removeAll();
        panelMain.add(panel, BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoMain = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        panelMenu = new javax.swing.JPanel();
        btnTasks = new javax.swing.JToggleButton();
        btnScores = new javax.swing.JToggleButton();
        btnStudents = new javax.swing.JToggleButton();
        panelMain = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        lblMateria = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(498, 502));
        setMinimumSize(new java.awt.Dimension(498, 502));
        setPreferredSize(new java.awt.Dimension(498, 502));

        panelMenu.setBackground(new java.awt.Color(102, 51, 255));

        btnTasks.setBackground(new java.awt.Color(102, 51, 255));
        grupoMain.add(btnTasks);
        btnTasks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTasks.setForeground(new java.awt.Color(255, 255, 255));
        btnTasks.setSelected(true);
        btnTasks.setText("Tareas");
        btnTasks.setActionCommand("Estudiantes");
        btnTasks.setBorder(null);
        btnTasks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTasksItemStateChanged(evt);
            }
        });
        btnTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTasksActionPerformed(evt);
            }
        });

        btnScores.setBackground(new java.awt.Color(102, 51, 255));
        grupoMain.add(btnScores);
        btnScores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnScores.setForeground(new java.awt.Color(255, 255, 255));
        btnScores.setText("Calificaciones");
        btnScores.setBorder(null);
        btnScores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnScoresItemStateChanged(evt);
            }
        });
        btnScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoresActionPerformed(evt);
            }
        });

        btnStudents.setBackground(new java.awt.Color(102, 51, 255));
        grupoMain.add(btnStudents);
        btnStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnStudents.setText("Estudiantes");
        btnStudents.setBorder(null);
        btnStudents.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnStudentsItemStateChanged(evt);
            }
        });
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(btnTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnScores, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScores, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        panelMain.setMaximumSize(new java.awt.Dimension(498, 429));
        panelMain.setMinimumSize(new java.awt.Dimension(498, 429));
        panelMain.setPreferredSize(new java.awt.Dimension(498, 429));
        panelMain.setLayout(new java.awt.BorderLayout());

        panelEncabezado.setBackground(new java.awt.Color(255, 102, 204));
        panelEncabezado.setMaximumSize(new java.awt.Dimension(498, 42));
        panelEncabezado.setMinimumSize(new java.awt.Dimension(498, 42));
        panelEncabezado.setPreferredSize(new java.awt.Dimension(498, 42));
        panelEncabezado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        lblMateria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMateria.setForeground(new java.awt.Color(255, 255, 255));
        lblMateria.setText("Materias");
        panelEncabezado.add(lblMateria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTasksItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTasksItemStateChanged
        toggleButtonBackground(btnTasks);
    }//GEN-LAST:event_btnTasksItemStateChanged

    private void btnScoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnScoresItemStateChanged
        toggleButtonBackground(btnScores);
    }//GEN-LAST:event_btnScoresItemStateChanged

    private void btnStudentsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnStudentsItemStateChanged
        toggleButtonBackground(btnStudents);
    }//GEN-LAST:event_btnStudentsItemStateChanged

    private void btnTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTasksActionPerformed
        initializePanel(new PanelTareas(idMateria, parent));
    }//GEN-LAST:event_btnTasksActionPerformed

    private void btnScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoresActionPerformed
        initializePanel(new PanelCalificacionTareas(idMateria));
    }//GEN-LAST:event_btnScoresActionPerformed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        initializePanel(new PanelEstudiantes(idMateria));
        
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void toggleButtonBackground(JToggleButton boton) {
        if (boton.isSelected()) boton.setBackground(new Color(102, 0, 255));
        else boton.setBackground(new Color(102, 51, 255));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnScores;
    private javax.swing.JToggleButton btnStudents;
    private javax.swing.JToggleButton btnTasks;
    private javax.swing.ButtonGroup grupoMain;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
